export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const OPEN_AD = "OPEN_AD";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const NAVIGATE = "NAVIGATE";
export const NAVIGATE_BACK = "NAVIGATE_BACK";
export const NEWS_LOADING = "NEWS_LOADING";
export const NEWS_LOADING_COMPLETE = "NEWS_LOADING_COMPLETE";

export const CACHING_START = "CACHING_START";
export const CACHING_DONE = "CACHING_DONE";
export const CACHING_UPDATE = "CACHING_UPDATE";
export const CACHING_ERROR = "CACHING_ERROR";
export const INTERNET_STATUS = "INTERNET_STATUS";

// screens while caching
export const SCREEN_INIT = "SCREEN_INIT";
export const SCREEN_NOTCACHED_NOINTERNET = "SCREEN_NOTCACHED_NOINTERNET";
export const SCREEN_CACHING_MAP = "SCREEN_CACHING_MAP";
export const SCREEN_CACHING_ERROR = "SCREEN_CACHING_ERROR";

// change of type or place in Locations
export const LOCATION_FILTER_CHANGE = "LOCATION_FILTER_CHANGE";
export const LOCATIONS_UPDATE_EN = "LOCATIONS_UPDATE_EN";
export const LOCATIONS_UPDATE_SR = "LOCATIONS_UPDATE_SR";
export const OPEN_LOCATION_TYPE = "OPEN_LOCATION_TYPE";
export const OPEN_LOCATION_PLACE = "OPEN_LOCATION_PLACE";

// fething good to know data
export const FETCH_GOOD_TO_KNOW_SUCCESS = "FETCH_GOOD_TO_KNOW_SUCCESS";

// fething categories data
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

// fething map data
export const FETCH_MAP_SUCCESS = "FETCH_MAP_SUCCESS";
