export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const OPEN_AD = "OPEN_AD";
export const NAVIGATE = "NAVIGATE";
export const NAVIGATE_BACK = "NAVIGATE_BACK";
export const NEWS_LOADING = "NEWS_LOADING";
export const NEWS_LOADING_COMPLETE = "NEWS_LOADING_COMPLETE";
