export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const OPEN_AD = "OPEN_AD";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const NAVIGATE = "NAVIGATE";
export const NAVIGATE_BACK = "NAVIGATE_BACK";
export const NEWS_LOADING = "NEWS_LOADING";
export const NEWS_LOADING_COMPLETE = "NEWS_LOADING_COMPLETE";
export const CACHING_START = "CACHING_START";
export const CACHING_DONE = "CACHING_DONE";
export const CACHING_UPDATE = "CACHING_UPDATE";
export const INTERNET_STATUS = "INTERNET_STATUS";

// screens while caching
export const SCREEN_INIT = "SCREEN_INIT";
export const SCREEN_NOTCACHED_NOINTERNET = "SCREEN_NOTCACHED_NOINTERNET";
export const SCREEN_CACHING_MAP = "SCREEN_CACHING_MAP";
export const SCREEN_CACHING_ERROR = "SCREEN_CACHING_ERROR";

// change of type or place in Locations
export const LOCATION_FILTER_CHANGE = "LOCATION_FILTER_CHANGE";
export const OPEN_LOCATION_TYPE = "OPEN_LOCATION_TYPE";
export const OPEN_LOCATION_PLACE = "OPEN_LOCATION_PLACE";
