# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fruskac' do
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec =>'../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', :path => '../node_modules/react-native'


  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    'Core',
    'DevSupport',
    'CxxBridge',
    'RCTImage'
  ]

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Mapbox
  pod 'react-native-mapbox-gl', :path => '../node_modules/@react-native-mapbox-gl/maps'
  
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'




  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'yoga'
              target.build_configurations.each do |config|
                  config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
                  config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
              end
          end
          if target.name == "React"
            target.remove_from_project
          end
          if target.name == "RNSVG"
              target.build_configurations.each do |config|
                  config.build_settings['GCC_NO_COMMON_BLOCKS'] = 'NO'
              end
          end
      end
  end


end
